# Generated by Django 5.0.3 on 2024-03-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_fantasy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='player_id',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
