# Generated by Django 5.0.3 on 2024-03-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_fantasy', '0002_player_player_id_team_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('top', 'Top'), ('jungle', 'Jungle'), ('mid', 'Mid'), ('bot', 'Bot'), ('support', 'Support')], default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='icon_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
