# Generated by Django 5.0.3 on 2024-03-25 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_fantasy', '0003_player_country_player_position_team_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstat',
            name='stat_name',
            field=models.CharField(max_length=70),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=70)),
                ('tournament', models.CharField(max_length=255)),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='league_fantasy.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='league_fantasy.team')),
            ],
        ),
        migrations.AddField(
            model_name='playerstat',
            name='game',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='league_fantasy.game'),
            preserve_default=False,
        ),
    ]
