# Generated by Django 5.0.3 on 2024-03-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_fantasy', '0007_playersynonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
