# Generated by Django 5.0.3 on 2024-03-26 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_fantasy', '0009_player_active_team_active_userdraft_userdraftplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdraft',
            name='score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlayerScorePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('time', models.DateTimeField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_fantasy.player')),
            ],
        ),
        migrations.CreateModel(
            name='UserDraftScorePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('time', models.DateTimeField()),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_fantasy.userdraft')),
            ],
        ),
    ]
