# Generated by Django 5.0.3 on 2024-03-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_fantasy', '0011_team_background_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdraft',
            name='colour',
            field=models.CharField(default='#000000', max_length=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='background_colour',
            field=models.CharField(default='#ffffff', max_length=10),
        ),
    ]
