# Generated by Django 5.0.3 on 2024-03-26 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_fantasy', '0012_userdraft_colour_alter_team_background_colour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
