# Generated by Django 5.0.3 on 2024-03-28 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_fantasy', '0014_leaderboard_leaderboardmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='country',
        ),
        migrations.RemoveField(
            model_name='player',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_id',
        ),
        migrations.AddField(
            model_name='game',
            name='game_duration',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='game',
            name='rpgid',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='statistics_loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 28, 23, 52, 54, 763419)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.IntegerField(max_length=70),
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='icon_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
