# Generated by Django 5.0.3 on 2024-03-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_fantasy', '0015_remove_game_game_id_remove_player_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='winner',
            field=models.IntegerField(),
        ),
    ]
