# Generated by Django 5.0.3 on 2024-03-29 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_fantasy', '0016_alter_game_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('top', 'Top'), ('jungle', 'Jungle'), ('mid', 'Mid'), ('bot', 'Bot'), ('support', 'Support')], max_length=70)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_fantasy.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_fantasy.player')),
            ],
        ),
    ]
