# Generated by Django 5.0.3 on 2024-03-29 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_fantasy', '0017_gameplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='league_fantasy.team'),
            preserve_default=False,
        ),
    ]
