# Generated by Django 5.0.3 on 2024-04-15 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_fantasy', '0019_team_region_tournament_disambig_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTournamentScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_fantasy.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_fantasy.tournament')),
            ],
        ),
    ]
