# Generated by Django 5.0.3 on 2024-04-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_fantasy', '0020_playertournamentscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertournamentscore',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
