# Generated by Django 5.0.3 on 2024-04-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_fantasy', '0022_player_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='overview_page',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
