# Generated by Django 5.0.3 on 2025-02-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_fantasy', '0024_userdraft_score_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='match_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
