# Generated by Django 5.0.3 on 2025-03-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_fantasy', '0025_game_match_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='overview_page',
            field=models.CharField(default='', max_length=255),
        ),
    ]
