# Generated by Django 5.0.3 on 2025-04-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_fantasy', '0026_team_overview_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('champion_id', models.IntegerField(primary_key=True, serialize=False)),
                ('champion_name', models.CharField(max_length=255)),
            ],
        ),
    ]
