# Generated by Django 5.0.3 on 2025-04-13 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_fantasy', '0027_champion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentChampion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_fantasy.champion')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league_fantasy.tournament')),
            ],
        ),
    ]
