# Generated by Django 5.0.3 on 2025-04-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_fantasy', '0028_tournamentchampion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentchampion',
            name='games',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournamentchampion',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
